### ISSUE TITLE
large time over threshold TPs causing potential problems

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#11]
we saw some very large TOT TPs in the recent VD coldbox test, and think that this may have been causing some issues on the trigger algorithms. @ArturSztuc put in a temporary branch (https://github.com/DUNE-DAQ/triggeralgs/tree/asztuc/tmp_tpthreshold_filter) to filter out TPs with TOT > 10% of the window length in the HMA alg, but need to decide on a more permanent solution here.

**Comment by ArturSztuc** [comment]
I guess we need to decide whether some form of large TOT filtering should be implemented at the readout stage or trigger, or maybe it's a matter of changing the TPG algo (maybe moving from static ADC threshold TPG to some self-adjusting ADC threshold algorithm?).

**Comment by wesketchum** [comment]
Right. I think this really requires some discussion. A few options to my mind, that are not mutually exclusive:

- "Drop" TPs that are of some unreasonable TOT (as you say, filter at readout)
- Cut off TPs from having some large TOT but enforcing some maximum TOT (e.g. if you're above threshold for 100 ticks, but you have a maximum set of 60 ticks, create two TPs, one of 60 ticks and another of 40 ticks, right next to each other)
- Prevent TPs with some unreasonable TOT from entering any trigger algorithm
- Prevent TPs from being considered in specific trigger algorithms.

Of course, there's also the desire for this not to happen. I believe the main cause here was due to some high low-frequency noise on certain channels. Of course those channels can/should be removed if they're known to be bad, or a better algorithm could be found for handling the pedestal. But I think we want to still make ourselves more immune to adverse effects like this while running if possible.

**Comment by wesketchum** [comment]
to be discussed with data selection experts on the right way to handle this.

**Comment by ArturSztuc** [comment]
I agree with you that we should be immune to this behaviour, despite that the real fix should be somewhere at the hardware level/pedestals/masking out channels. I think the cut-off (with your example of 100tick TP being split into 60tick and 40tick) makes most sense, but that's without my full understanding of the potential consequences for real physics events that might contribute to this.

This solution could perhaps also help with buffering issues... e.g. if a TP has TOT of 50,000 ticks, and being split into a bunch of 10,000 ticks (or 20,000, 5,000, whatever), we might see less issues resulting from the combination of TPs having to be sorted in time, and some TPs taking very long time to be made (because of that large TOT).

**Comment by ArturSztuc** [comment]
The more I think about this, the more I think the large TOT TP cull should be at the readout level. Large TOT TPs will cause issues in the trigger even if we filter them out at the algorithm level:

Large TOT TPs are in the TPSet we receive that is sorted based on the tp's `start_time`, and are buffered straight away. But with TOT of, say, 50,000 ticks, it means that this TP must have been buffered at least 50,000 after it's start time, holding up the remaining TPs from being sorted into a TPSet. This also means, that if there's a second TP that only appeared, say, 100 ticks after start time of the previous one, it will still wait for 50,000 ticks before it's put into the TPSet and send to the trigger. The point is, these large TOT TPs are actually increasing latencies/delaying everything within their window. We then send a trigger request, but after we receive that large TOT TP we also receive many, many other TPs that are within the large TOT window, and the TPs we actually want might go out of scope in the buffer (which only holds ~100,000 TPs at any time, I believe).

If we instead chop large TOT TP in the TPG algorithm into smaller chunks as in your option no. 2, we will get rid of that extra latency. Again, not sure if that's correct physics-wise though...

Mybe @hristovaivana can weigh in on this too.

**Comment by hristovaivana** [comment]
I will definitely need to think more, but the more I think about this issue and now that Artur pinged me, the more I tend to agree with Artur. I think he is referring to this logic [here](https://github.com/DUNE-DAQ/fdreadoutlibs/blob/d0e67e3387b140c460a4e83f29ef860f31e330ca/src/TPCTPRequestHandler.cpp#L143) when he mentioned `start_time`. The point is that any TP parameter that involves a timestamp is not simply a TP parameter that can be or can not be part of the trigger algorithm logic (depending on the which algorithm we choose to run) but it is a fundamental quantity that defines the way these TPs flow through the system, way before they even reach the trigger. I think that's Artur's point, if I understood it. The ToT is not simply a TP anomaly, it is a readout system anomaly (unless it's a subtle bug/feature), in a way, and therefore it shall be treated closer to the source, rather than later/further away.

**Comment by wesketchum** [comment]
as discussed in ops meeting, should have protection for TPs on the TPChanelFilter side

**Comment by wesketchum** [comment]
Artur has a new branch that can do some filtering on the trigger side, but needs discussion/coordination with the TPG group to finalize plans.

**Comment by ArturSztuc** [comment]
The proposed branches:
https://github.com/DUNE-DAQ/trigger/compare/production/v4...asztuc/max_time_over_threshold
https://github.com/DUNE-DAQ/daqconf/compare/production/v4...asztuc/trigger_max_tot_filtering
as above through, needs testing, maybe some refining, discussions with TPG team etc. before any PR.

**Comment by ArturSztuc** [comment]
Pull request ready:
trigger: https://github.com/DUNE-DAQ/trigger/pull/284
daqconf: https://github.com/DUNE-DAQ/trigger/pull/273

**Comment by ArturSztuc** [comment]
@wesketchum these PRs are now merged, so the trigger application should be able to deal with this.
The issue probably shouldn't be closed until the readout can also split these TPs into multiple.

@adam-abed-abud and @roland-sipos should know more about progress here, from what I understand there are already plans in the readout to work on this.

**Comment by wesketchum** [comment]
Closing as there is no immediate further work planned on this outside of studying/understanding any long TOT TPs.
