### ISSUE TITLE
elog automatic posting not working

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#4]
Automated posts at run start to the elog from nano04rc are not working due to complaints about an outdated certificate (I think). Work underway to find a more sustainable elog instance.

**Comment by roland-sipos** [comment]
Problem statement:

- The elog instances (pdsp, np-vd-colbox and others) are hosted on an EP-DT-DI owned OpenStack tenant at CERN. Due to the lack of detector operations, the maintainer's departure, these services were not maintained for over 2 years. Every aspect of the web service needs manual interactions: certificate renewal, database updates, puppet manifest updates, firewall open requests, etc.
- As EP-DT-DI has other elog instances that need to keep running, an initiaitve started in the section to move back the webservices from CERN OpenStack to CERN PaaS (OpenShift).
- A test instance was launched to see that all the necessary functionalities are restored using the new SSO proxy and new Elisa software RPM in a docker container. Testing of this is ongoing. 
- When the automatic posting from nanorc works towards the PaaS instance, we stop the VM instance and update instructions and advertise that the new ELOG URL.

**Comment by plasorak** [comment]
This should now be fixed on the first RC.

**Comment by wesketchum** [comment]
Got this error when trying just now:
```
Couldn't make an entry to elisa, do it yourself manually at https://pdsp-elog.app.cern.ch                                            core.py:348
                    Error text:                                                                                                                                     
                    Invalid header value b'# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This is a generated file!  Do not             
                    edit.\n\nauth.cern.ch\tFALSE\t/\tTRUE\t1707830783\tLBLEVEL1\tk8s_authzsvc_prod_c-Node1\nauth.cern.ch\tFALSE\t/\tFALSE\t1707830783\tk            
                    eycloak-instance\t64bf6fef89385255\nauth.cern.ch\tFALSE\t/auth/realms/cern/\tTRUE\t1707830783\tAUTH_SESSION_ID\t7d1d6ce5-0dbe-496b-b            
                    c96-13db5da6ff1f.keycloak-v20-0-43468\nauth.cern.ch\tFALSE\t/auth/realms/cern/\tFALSE\t1707830783\tAUTH_SESSION_ID_LEGACY\t7d1d6ce5-            
                    0dbe-496b-bc96-13db5da6ff1f.keycloak-v20-0-43468\nauth.cern.ch\tFALSE\t/auth/realms/cern/\tFALSE\t1707830783\tKC_RESTART\teyJhbGciOi            
                    ...'                         
```

**Comment by plasorak** [comment]
do you have 2FA-alwayson?

**Comment by wesketchum** [comment]
2FA always on is incompatible with how things are being done now. Solution suggested to Enrico from CERN IT was creation of a service account that won't require 2FA, and so automated elog entries will come from this new services account. We'll potentially lose verification of the ID of the user on posting to the elog, though we can still post the user name from the message so still retain much of that.

Technically then there's no need for the user to login with kerberos into nanorc, but will need to decide whether to keep that or not.

Needs new user added to all the right egroups and such ... after that not complicated, but timeline for that is a bit unknown.

**Comment by wesketchum** [comment]
now working in the fddaq-v4.3.0-rc3 release candidate.
